"use client"

import Navigetion from "../component/Navigation"
import { usePathname } from "next/navigation"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children, nav }) {
  const path = usePathname();

  return (
    <html lang="en">
      <body>
        {path !== "/about-us" ? <Navigetion/> : null}
        {children}
      </body>
    </html>
  )
}
